apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eq4652ziq-go 
  janus-idp.io/tekton: eq4652ziq-go
  backstage.io/kubernetes-id: eq4652ziq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eq4652ziq-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  