apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: eq4652ziq-go-gitops
  description: This is GitOps manifest for eq4652ziq-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: eq4652ziq-go
    janus-idp.io/tekton: eq4652ziq-go 
    backstage.io/kubernetes-id: eq4652ziq-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:eq4652ziq-go
